

export class Personal{
    constructor(
    public id_personal?: number,
    public apellido_1?: string,
    public apellido_2?: string,
    public nombre_1?: string,
    public nombre_2?: string,
    public nombre_3?: string,
    public dni?: number,
    public fecha_nacimiento?: Date,
    public fecha_ingreso?: Date,
    public ultimo_ascenso?: Date,
    public legajo?: number,
    public cuil?: string,
    public sexo_id?: number,
    public sexo?: string,
    public estado_civil_id?: number,
    public estado_civil?: string,
    public destino_id?: number,
    public destino?: string,
    public departamento_id? : number,
    public departamento?: string,
    public division_id? : number,
    public division?: string,
    public sector_id? : number,
    public sector? : string,
    public seccion_guardia_id? : number,
    public seccion_guardia? : string,
    public funcion_id? : number,
    public funcion?: string,
    public escalafon_id? : number,
    public escalafon?: string,
    public escala_jerarquica_id? : number,
    public escala_jerarquica?: string,
    public grado_id? : number,
    public grado?: string,
    public nacionalidad? : string,
    public domicilio? : string,
    public provincia_id? : number,
    public provincia? : string,
    public departamento_provincial_id? : number,
    public departamento_provincial?: string,
    public municipio_id? : number,
    public municipio?: string,
    public ciudad_id? : number,
    public ciudad?: string,
    public nivel_educativo_id?: number,
    public nivel_educativo?: string,
    public telefonos? : string,
    public email? : string,
    public altura?: number,
    public peso?: number,
    public registrado_por?: number,
    public situacion_id? : number,
    public situacion? : string,
    public foto?: string,
    public pdfs?: any[]
    ){}

}

export interface IPersonalTable{
    id_personal: number,
    apellido_1: string,
    apellido_2: string,
    nombre_1: string,
    nombre_2: string,
    nombre_3: string,
    dni: number,
    legajo: number,
    sexo: string,
    estado_civil: string,
    destino: string,
    departamento: string,
    division: string,
    sector : string,
    seccion_guardia : string,
    funcion_id : number,
    escalafon: string,
    escala_jerarquica: string,
    grado: string,
    nacionalidad : string,
    domicilio : string,
    provincia : string,
    departamento_provincial: string,
    municipio: string,
    ciudad: string,
    nivel_educativo: string,
    situacion : string,
    foto: string,
}